name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Check for uncommitted changes
        run: git status

      - name: Stage and Commit changes if necessary
        run: |
          git add .
          git commit -m "Committing changes"

      - name: Publish package
        run: npx jsr publish --allow-dirty
